config/routes.rb
Rails.application.routes.draw do

  resources :artists

   get 'welcome', to: 'welcome#index'

end

app/models/album.rb
class Album < ActiveRecord::Base

	belongs_to :artist
	has_many :songs, dependent: :destroy

end
		

app/models/artist.rb
class Artist < ActiveRecord::Base

	has_many :albums, dependent: :destroy
	
end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :album
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


	def index
		@artists=Artist.all
	end

	def show
		@artist=Artist.find(params[:id])
		@albums=@artist.albums

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<div class="container">
	<div class="row">
		<div class="artists-list">
		<% @artists.each do |a| %>
			<div class="artist col-md-3">
					<img src="<%= a.image_url %>" alt="" class="img_artist_1 center-block"  >
					<h3 class="text-center"><%= a.name %></h3>
					<%= link_to 'Ver mas', artist_path(a), class:'btn btn-primary btn-block' %>
				</div>
			<% end %>
		</div>
 	</div>	
	
</div>

app/views/artists/show.html.erb
<div class="container-fluid">
		
	<div class="row">
		
		<div class="col-md-6">
			<h1 class="text-left"><%= @artist.name  %></h1>
			<h1 class="text-left">Albums (<%= @albums.count  %>)</h1>
			<br>


			<% @albums.each do |album| %>
				<div class="col-md-4 album">
					<img src="<%= album.image_url %>" alt="" class="img_album center-block">
					<p class="text-center" ><%= album.name %></p>
					<p class="text-center" ><%= album.released_at %></p>
					
				</div>
			<% end %>
		</div>



		<div class="col-md-6 ">
			
			<img src="<%= @artist.image_url%>" alt="" class="img_artist_2 center-block">
		</div>
	

	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicaMusica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Real Music</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mi cuenta<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<%= yield %>

</body>
</html>